Assignment 1
------------

1.	Import the Numpy package under the name np

In [16]:
import numpy as np

2.	Create a null vector of size 10

In [4]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3.	Create a null vector of size 10 but the fifth value which is 1

In [9]:
b=a.copy()
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4.	Create a vector with values ranging from 10 to 49

In [12]:
c=np.arange(10,49)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

5.	Reverse a vector (the first element becomes last)

In [23]:
c1=np.flip(c)
c1

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

6.	Create a 3x3 matrix with values ranging from 0 to 8

In [40]:
d=np.matrix(range(9))
d.shape=(3,3)
d

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

7.	Find indices of non¬zero elements from [1,2,0,0,4,0]

In [44]:
e=[1,2,0,0,4,0]
non_zero_indices=[e.index(i)for i in e if i!=0]
non_zero_indices

[0, 1, 4]

8.	Create a 3x3x3 array with random values

In [52]:
import random
f=np.random.randint(5,50,(3,3,3))
f

array([[[18, 27, 31],
        [14, 23, 12],
        [25, 15, 42]],

       [[22, 21, 12],
        [16, 19, 34],
        [29, 45, 20]],

       [[ 8, 19, 12],
        [33, 22, 44],
        [22, 28, 39]]])

9.	Create a random vector of size 30 and find the mean value

In [59]:
g=np.array([random.randint(1,100)for i in range(30)])
g
g.mean()

53.3

10.	Create a 2d array with 1 on the border and 0 inside

In [67]:
h=np.array([[0,0,0],[0,1,0],[1,1,1]])
print("2D array\n",h)
print("Dimension: ",h.ndim)

2D array
 [[0 0 0]
 [0 1 0]
 [1 1 1]]
Dimension:  2


11.	Create an 8x8 matrix and fill it with a checkerboard pattern

In [87]:
k=np.ones((8,8))
k[1::2,::2]=0
k[::2,1::2]=0
k

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

12.	What is the major difference between sets, lists, tuples, and dictionaries?

sets
------
-denoted by {}
-unordered data structure
-no duplicates
-mutable
-Boolean is excluded

lists
------
-denoted by []
-ordered data structure
-allow all data types
-allow duplicates
-mutable

tuples
---------
-denoted by ()
-ordered data structure
-allow all data types
-allow duplicates
-immutable

dictionaries
-----------------
-denoted by {}
-mapping based data structure,pairwise elements
-unordered data structure
-allow all data types
-overwrite the duplicates
-mutable



13.	Print first 10 natural numbers using while loop

In [91]:
n=0
while n!=10:
    print(n)
    n+=1

0
1
2
3
4
5
6
7
8
9


14.	Print the numbers -10 to -1 using for loop.

In [95]:
for i in range(-10,0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


15.	Print the message “Done” after successful execution of any for loop. 

In [5]:
for i in range(3):
    input("Please enter a number from 1 to 10: ")
    if i%2==0:
        print("Try again")      
    else:
        print("Done")
        break

Please enter a number from 1 to 10: 4
Try again
Please enter a number from 1 to 10: 5
Done


16.	Create a random vector of size 10 and sort it

In [30]:
l=np.random.randint(1,100,(10))
np.sort(l,axis=0)

array([30, 32, 60, 65, 70, 73, 78, 80, 87, 97])

17.	Execute any three math functions using numpy.

In [39]:
print("Mean =", l.mean())
print("Standard Deviation =", round(l.std(),2))
print("Total =", l.sum())

Mean = 67.2
Standard Deviation = 20.69
Total = 672
